place1 = input('A place you hate: ')
verb1 = input('A continuous verb(e.g. playing): ')
noun1 = input('A noun(a boring thing):')
travel1 = input('A form of travelling, in past tense(e.g. flied, took a train, walked): ')
place2 = input('A place you like: ')
adjective = input('An adjective: ')
verb2 = input('A verb in past tense: ')
noun2 = input('A noun: ')
food1 = input('Your favourite food: ')
food2 = input('Your least favourite food: ')
name = input("Your best friend's name: ")
enemy = input('Someone you are both afraid of and hate: ')
print('-'*20)
print('One day,', name, 'and I were', verb1, 'with a/an', noun1, 'in', place1+'.')
print(name, 'suggested we go to', place2, 'as it is', adjective+'.\nI agreed.')
print('When we', travel1, 'there, I found out that the place was really', adjective+'.')
print('We', verb2, 'with', noun2, 'there and I really enjoyed it.')
print('I was happy that I was able to taste', food1, 'for lunch and it was delicious!')
print('However, we still have to go back to', place1, 'where we will have', food2, 'for dinner, and we have to go there fast before', enemy, 'discovers and something bad will happen and ruin our day!')
print('We managed to go back to', place1, 'before', enemy, 'discovers it. Phew! What a day!')
print('-'*20)
